package gui.dialog;

import bus.KeHoachTourBUS;
import dto.ChiTietHanhKhachDTO;
import dto.DatTourDTO;
import gui.panel.ChiTietHanhKhachPanel;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import utils.FormatDate;

public class AddDatTourDialog extends javax.swing.JDialog {

    private ArrayList<String> cardNames = new ArrayList<>();
    private ArrayList<ChiTietHanhKhachDTO> dsChiTietHK = new ArrayList<>();
    private ArrayList<ChiTietHanhKhachPanel> dsPanelChiTiet = new ArrayList<>();
    private int cardIndex = 0;
    private float giaVe;
    private DatTourDTO datTourDTO;
    private boolean save = false;

    public AddDatTourDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        cards.add(panelThongTin, "cardNhapThongTin");
        cardNames.add("cardNhapThongTin");
        spSoLuong.setModel(new SpinnerNumberModel(1, 1, 50, 1));
        btnBack.setVisible(false);
        txtNgayDat.setText(FormatDate.toString(LocalDate.now(), "dd/MM/yyyy"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaKHTour = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgayDat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spSoLuong = new javax.swing.JSpinner();
        panelXacNhan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSLVe = new javax.swing.JTextField();
        cards = new javax.swing.JPanel();
        btnCancel = new gui.components.MyButton();
        btnNext = new gui.components.MyButton();
        btnBack = new gui.components.MyButton();

        panelThongTin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Mã kế hoạch tour");

        txtMaKHTour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Mã khách hàng");

        txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Ngày đặt");

        txtNgayDat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Số lượng");

        javax.swing.GroupLayout panelThongTinLayout = new javax.swing.GroupLayout(panelThongTin);
        panelThongTin.setLayout(panelThongTinLayout);
        panelThongTinLayout.setHorizontalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtMaKHTour, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelThongTinLayout.createSequentialGroup()
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(spSoLuong))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelThongTinLayout.setVerticalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKHTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelXacNhan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Tổng tiền");

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("VNĐ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Vui lòng xác nhận");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Số lượng vé");

        txtSLVe.setEditable(false);
        txtSLVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelXacNhanLayout = new javax.swing.GroupLayout(panelXacNhan);
        panelXacNhan.setLayout(panelXacNhanLayout);
        panelXacNhanLayout.setHorizontalGroup(
            panelXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelXacNhanLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(panelXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelXacNhanLayout.createSequentialGroup()
                        .addGroup(panelXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(panelXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSLVe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelXacNhanLayout.createSequentialGroup()
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelXacNhanLayout.setVerticalGroup(
            panelXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXacNhanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(panelXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSLVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đặt tour");
        setBackground(new java.awt.Color(255, 255, 255));

        cards.setLayout(new java.awt.CardLayout());

        btnCancel.setBackground(new java.awt.Color(255, 102, 102));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 255, 153));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (cardIndex == 0) {
            // sau khi có số lượng -> chèn các panel nhập thông tin hành khách theo số lượng
            if (checkValidateCardThongTin() == false) {
                return;
            }

            // lấy thông tin đặt tour
            datTourDTO = new DatTourDTO();
            datTourDTO.setMaKHTour(Integer.parseInt(txtMaKHTour.getText()));
            datTourDTO.setMaKH(Integer.parseInt(txtMaKH.getText()));
            giaVe = new KeHoachTourBUS().getKeHoachTourById(datTourDTO.getMaKHTour()).getGiaVe();
            datTourDTO.setSoLuong((int) spSoLuong.getValue());
            cards.removeAll();
            cards.add(panelThongTin, "cardNhapThongTin");
            cardNames.clear();
            cardNames.add("cardNhapThongTin");

            // thêm chi tiết
            dsPanelChiTiet.clear();
            for (int i = 0; i < (int) spSoLuong.getValue(); i++) {
                dsPanelChiTiet.add(new ChiTietHanhKhachPanel(i + 1));
                String cardName = "cardChiTiet" + (i + 1);
                cardNames.add(cardName);
                cards.add(dsPanelChiTiet.getLast(), cardName);
            }
            String name = "cardXacNhan";
            cardNames.add(name);
            cards.add(panelXacNhan, name);
            btnBack.setVisible(true);
            changeCard(1);
        } else if (cardIndex <= datTourDTO.getSoLuong()) {
            ChiTietHanhKhachPanel panel = dsPanelChiTiet.get(cardIndex - 1);
            if (panel.validateData()) {
                if (cardIndex == datTourDTO.getSoLuong()) {
                    btnNext.setText("SUBMIT");
                    txtSLVe.setText(String.valueOf((int) spSoLuong.getValue()));
                    float total = 0;
                    for (ChiTietHanhKhachPanel e: dsPanelChiTiet) {
                        total += e.tinhGiaVe(giaVe);
                    };
                    txtTongTien.setText(new DecimalFormat("#,###.##").format(total));
                    datTourDTO.setTongTien(total);
                }
                changeCard(1);
            }
        } else {
            doSubmit();
        }

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (cardIndex == 1) {
            btnBack.setVisible(false);
        }
        btnNext.setText("NEXT");
        changeCard(-1);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int result = JOptionPane.showConfirmDialog(
                getOwner(),
                "Bạn có chắc chắn muốn thoát?",
                "Xác nhận",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void doSubmit() {
        save = true;
        dispose();
    }

    public DatTourDTO getInputData() {
        return datTourDTO;
    }
    
    public ArrayList<ChiTietHanhKhachDTO> getChiTietHanhKhachList() {
        for (int i=0; i<dsPanelChiTiet.size(); i++) {
            dsChiTietHK.add(dsPanelChiTiet.get(i).getInput());
        }
        return dsChiTietHK;
    }

    public boolean isSave() {
        return this.save;
    }

    private void changeCard(int step) {
        cardIndex += step;
        CardLayout layout = (CardLayout) cards.getLayout();
        layout.show(cards, cardNames.get(cardIndex));
    }

    private boolean checkValidateCardThongTin() {
        // Validate maKHTour
        if (txtMaKHTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã kế hoạch tour không được để trống!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            txtMaKHTour.requestFocus();
            return false;
        }
        try {
            String maKHTour = txtMaKHTour.getText().trim();
            Integer.valueOf(maKHTour);
            txtMaKHTour.setText(maKHTour);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã kế hoạch tour phải là số nguyên!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            txtMaKHTour.requestFocus();
            return false;
        }

        // Validate maKH
        if (txtMaKH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng không được để trống!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            txtMaKH.requestFocus();
            return false;
        }
        try {
            String maKH = txtMaKH.getText().trim();
            Integer.valueOf(maKH);
            txtMaKH.setText(maKH);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng phải là số nguyên!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            txtMaKH.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDatTourDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDatTourDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDatTourDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDatTourDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDatTourDialog dialog = new AddDatTourDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.components.MyButton btnBack;
    private gui.components.MyButton btnCancel;
    private gui.components.MyButton btnNext;
    private javax.swing.JPanel cards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelThongTin;
    private javax.swing.JPanel panelXacNhan;
    private javax.swing.JSpinner spSoLuong;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaKHTour;
    private javax.swing.JTextField txtNgayDat;
    private javax.swing.JTextField txtSLVe;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
