package gui.dialog;

import dto.KeHoachTourDTO;
import dto.TourDTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import bus.TourBUS;
import enums.TrangThaiKeHoachTour;
import utils.FormatDate;

public class KeHoachTourDialog extends javax.swing.JDialog {

    private boolean save;

    /**
     * Creates new form TourDialog
     *
     * @param parent
     */
    public KeHoachTourDialog(java.awt.Frame parent) {
        super(parent, "Nhập thông tin kế hoạch tour", true);
        // Thêm vào phương thức constructor hoặc initComponents
        initComponents();
        jdcThoiGianBD.setDateFormatString("yyyy-MM-dd");
        prepareDialog();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new gui.components.MyButton();
        btnCancel = new gui.components.MyButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTongChiPhi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jdcThoiGianBD = new com.toedter.calendar.JDateChooser();
        cbMaTour = new gui.components.CustomComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtDaDat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtToiDa = new javax.swing.JTextField();
        cbTrangThai = new gui.components.CustomComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Mã Tour");

        btnSubmit.setBackground(new java.awt.Color(51, 204, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Thời gian bắt đầu");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Tổng chi phí");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Trạng thái");

        cbMaTour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã Tour - Tên Tour" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Số vé đã đặt");

        txtDaDat.setText("0");
        txtDaDat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDaDat.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Số vé tối đa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(txtTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(cbMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdcThoiGianBD, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))
                            .addComponent(txtDaDat)
                            .addComponent(txtToiDa)
                            .addComponent(cbTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jdcThoiGianBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDaDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
        int result = JOptionPane.showConfirmDialog(
                getOwner(),
                "Bạn có chắc chắn muốn thoát?",
                "Xác nhận",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            dispose();
        }
    }// GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSubmitActionPerformed
        if (cbMaTour.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Mã tour không được để trống!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            cbMaTour.requestFocus();
            return;
        }
        try {
            String maTourText = cbMaTour.getSelectedItem().toString().split(" - ")[0].trim();
            Integer.valueOf(maTourText);
        } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Mã tour phải là số nguyên!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            cbMaTour.requestFocus();
            return;
        }
        if (jdcThoiGianBD.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Thời gian bắt đầu không được để trống!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            jdcThoiGianBD.requestFocus();
            return;
        }
        if (txtDaDat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số lượng vé đã đặt không được để trống", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtDaDat.requestFocus();
            return;
        }
        try {
            Integer.valueOf(txtDaDat.getText().trim());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Số lượng vé đã đặt phải là số nguyên", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtDaDat.requestFocus();
            return;
        }
        if (txtToiDa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số lượng vé tối đa không được để trống", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtToiDa.requestFocus();
            return;
        }
        try {
            Integer.valueOf(txtToiDa.getText().trim());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Số lượng vé tối đa phải là số nguyên", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtToiDa.requestFocus();
            return;
        }
        if (Integer.valueOf(txtDaDat.getText().trim()) > Integer.valueOf(txtToiDa.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Số lượng vé tối đa không được ít hơn số vé đã đặt", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtToiDa.requestFocus();
            return;
        }
        
        if (txtTongChiPhi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tổng chi phí không được để trống!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            txtTongChiPhi.requestFocus();
            return;
        }
        try {
            Float.valueOf(txtTongChiPhi.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tổng chi phí phải là số!", "Lỗi nhập liệu",
                    JOptionPane.WARNING_MESSAGE);
            txtTongChiPhi.requestFocus();
            return;
        }

        save = true;
        dispose();
    }// GEN-LAST:event_btnSubmitActionPerformed

    public void loadData(KeHoachTourDTO khTour) {
        TourDTO tour = new TourBUS().getTourById(khTour.getMaTour());
        cbMaTour.setSelectedItem(tour.getMaTour() + " - " + tour.getTenTour());
        jdcThoiGianBD.setDate(FormatDate.localDateToDate(khTour.getThoiGianBD()));
        txtDaDat.setText(String.valueOf(khTour.getSlDaDat()));
        txtToiDa.setText(String.valueOf(khTour.getSlToiDa()));
        cbTrangThai.setSelectedItem(khTour.getTrangThai());
        txtTongChiPhi.setText(String.format("%.0f", khTour.getTongChiPhi()));
    }

    public boolean isSave() {
        return this.save;
    }

    @SuppressWarnings("unchecked")
    /**
     * Phương thức này nạp danh sách tour vào ComboBox Format hiển thị: "maTour
     * - tenTour"
     */
    private void prepareDialog() {
        // load data for matour combobox
        ArrayList<TourDTO> dsTour = new TourBUS().getDsTour();
        if (dsTour == null || dsTour.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có tour nào trong danh sách!", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Tạo mảng String để lưu các item của ComboBox
        String[] items = new String[dsTour.size()];
        // Định dạng "maTour - tenTour" cho mỗi item
        for (int i = 0; i < dsTour.size(); i++) {
            TourDTO tour = dsTour.get(i);
            items[i] = tour.getMaTour() + " - " + tour.getTenTour();
        }
        // Tạo model mới với các item đã định dạng
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(items);
        // Áp dụng model mới cho ComboBox
        cbMaTour.setModel(model);
        
        // load data for trangthai
        cbTrangThai.setModel(new DefaultComboBoxModel<>(TrangThaiKeHoachTour.values()));
    }

    public KeHoachTourDTO getInputData() {
        KeHoachTourDTO khTour = new KeHoachTourDTO();
        String maTourText = cbMaTour.getSelectedItem().toString().split(" - ")[0].trim();
        khTour.setMaTour(Integer.parseInt(maTourText));
        khTour.setThoiGianBD(FormatDate.dateToLocalDate(jdcThoiGianBD.getDate()));
        khTour.setTrangThai((TrangThaiKeHoachTour)cbTrangThai.getSelectedItem());
        khTour.setSlDaDat(Integer.parseInt(txtDaDat.getText()));
        khTour.setSlToiDa(Integer.parseInt(txtToiDa.getText()));
        khTour.setTongChiPhi(Float.parseFloat(txtTongChiPhi.getText()));
        return khTour;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.components.MyButton btnCancel;
    private gui.components.MyButton btnSubmit;
    private gui.components.CustomComboBox cbMaTour;
    private gui.components.CustomComboBox cbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private com.toedter.calendar.JDateChooser jdcThoiGianBD;
    private javax.swing.JTextField txtDaDat;
    private javax.swing.JTextField txtToiDa;
    private javax.swing.JTextField txtTongChiPhi;
    // End of variables declaration//GEN-END:variables
}
