package gui.dialog;

import dto.KeHoachTourDTO;
import javax.swing.JOptionPane;

public class KeHoachTourDialog extends javax.swing.JDialog {

    private boolean save;

    /**
     * Creates new form TourDialog
     *
     * @param parent
     */
    public KeHoachTourDialog(java.awt.Frame parent) {
        super(parent, "Nhập thông tin kế hoạch tour", true);
        // Thêm vào phương thức constructor hoặc initComponents
        initComponents();
        jdcThoiGianBD.setDateFormatString("yyyy-MM-dd");
        jdcThoiGianKT.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JTextField();
        btnSubmit = new gui.components.MyButton();
        btnCancel = new gui.components.MyButton();
        txtMaKHTour = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTongChiPhi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jdcThoiGianBD = new com.toedter.calendar.JDateChooser();
        jdcThoiGianKT = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Mã Tour");

        btnSubmit.setBackground(new java.awt.Color(51, 204, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Mã Kế hoạch Tour");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Thời gian kết thúc");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Thời gian bắt đầu");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Tổng chi phí");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Trạng thái");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(txtMaKHTour, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(txtTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcThoiGianBD, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jdcThoiGianKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(123, 123, 123)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaKHTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jdcThoiGianBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jdcThoiGianKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int result = JOptionPane.showConfirmDialog(
                getOwner(),
                "Bạn có chắc chắn muốn thoát?",
                "Xác nhận",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION)
            dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (txtMaTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã tour không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtMaTour.requestFocus();
            return;
        }
        try {
            Integer.valueOf(txtMaTour.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã tour phải là số nguyên!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtMaTour.requestFocus();
            return;
        }
        if (txtMaKHTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã kế hoạch tour không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtMaKHTour.requestFocus();
            return;
        }
        try {
            Integer.valueOf(txtMaKHTour.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã kế hoạch tour là số nguyên!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtMaKHTour.requestFocus();
            return;
        }
        if (jdcThoiGianBD.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Thời gian bắt đầu không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            jdcThoiGianBD.requestFocus();
        }
        if (jdcThoiGianKT.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Thời gian kết thúc không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            jdcThoiGianKT.requestFocus();
        }
        if (txtTrangThai.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Trạng thái không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtTrangThai.requestFocus();
            return;
        }
        if (txtTongChiPhi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tổng chi phí không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtTongChiPhi.requestFocus();
            return;
        }
        try {
            Float.valueOf(txtTongChiPhi.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tổng chi phí phải là số!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtTongChiPhi.requestFocus();
            return;
        }
        
        
        save = true;
        dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    public void loadData(KeHoachTourDTO khTour) {
        txtMaTour.setText(String.valueOf(khTour.getMaTour()));
        txtMaKHTour.setText(String.valueOf(khTour.getMaKHTour()));
        jdcThoiGianBD.setDate(khTour.getThoiGianBD());
        jdcThoiGianKT.setDate(khTour.getThoiGianKT());
        txtTrangThai.setText(khTour.getTrangThai());
        txtTongChiPhi.setText(String.valueOf(khTour.getTongChiPhi()));
    }

    public boolean isSave() {
        return this.save;
    }
    
    public KeHoachTourDTO getInputData() {
        KeHoachTourDTO khTour = new KeHoachTourDTO();
        khTour.setMaTour(Integer.parseInt(txtMaTour.getText()));
        khTour.setMaKHTour(Integer.parseInt(txtMaKHTour.getText()));
        khTour.setThoiGianBD(jdcThoiGianBD.getDate());
        khTour.setThoiGianKT(jdcThoiGianKT.getDate());
        khTour.setTrangThai(txtTrangThai.getText());
        khTour.setTongChiPhi(Float.parseFloat(txtTongChiPhi.getText()));
        return khTour;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.components.MyButton btnCancel;
    private gui.components.MyButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdcThoiGianBD;
    private com.toedter.calendar.JDateChooser jdcThoiGianKT;
    private javax.swing.JTextField txtMaKHTour;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtTongChiPhi;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
