package gui.Dialog;

import model.TourDTO;
import javax.swing.JOptionPane;

public class TourDialog extends javax.swing.JDialog {

    private boolean save;

    /**
     * Creates new form TourDialog
     *
     * @param parent
     */
    public TourDialog(java.awt.Frame parent) {
        super(parent, "Nhập thông tin tour", true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSoNgay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoDem = new javax.swing.JTextField();
        txtTinhTrang = new javax.swing.JTextField();
        txtDiemKH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();
        txtDiemDen = new javax.swing.JTextField();
        txtGiaTour = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbLoaiTour = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnSubmit = new gui.Components.MyButton();
        btnCancel = new gui.Components.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Số ngày");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Số đêm");

        txtSoNgay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Tình trạng");

        txtSoDem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtDiemKH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Tên Tour");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Điểm khởi hành");

        txtTenTour.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtDiemDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtGiaTour.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Điểm đến");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Giá tour");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Loại tour");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mô tả");

        cbLoaiTour.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMoTa.setLineWrap(true);
        txtMoTa.setRows(5);
        txtMoTa.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtMoTa);

        btnSubmit.setBackground(new java.awt.Color(51, 204, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoDem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenTour)
                    .addComponent(txtGiaTour)
                    .addComponent(txtTinhTrang)
                    .addComponent(jScrollPane1)
                    .addComponent(txtDiemKH)
                    .addComponent(txtDiemDen)
                    .addComponent(cbLoaiTour, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoaiTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int result = JOptionPane.showConfirmDialog(
                getOwner(),
                "Bạn có chắc chắn muốn thoát?",
                "Xác nhận",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION)
            dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (txtTenTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên tour không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtTenTour.requestFocus();
            return;
        }
        if (txtGiaTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá tour không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtGiaTour.requestFocus();
            return;
        }
        try {
            Float.valueOf(txtGiaTour.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá tour phải là số!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtGiaTour.requestFocus();
            return;
        }
        if (txtTinhTrang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số ngày không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtTinhTrang.requestFocus();
            return;
        }
        if (txtMoTa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số ngày không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtMoTa.requestFocus();
            return;
        }
        if (txtDiemKH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số ngày không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtDiemKH.requestFocus();
            return;
        }
        if (txtDiemDen.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số ngày không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtDiemDen.requestFocus();
            return;
        }
        if (cbLoaiTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số ngày không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            cbLoaiTour.requestFocus();
            return;
        }
        if (txtSoNgay.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số ngày không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtSoNgay.requestFocus();
            return;
        }
        try {
            Integer.valueOf(txtSoNgay.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số ngày phải là số nguyên!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtSoNgay.requestFocus();
            return;
        }
        if (txtSoDem.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số đêm không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtSoDem.requestFocus();
            return;
        }
        try {
            Integer.valueOf(txtSoDem.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số đêm phải là số nguyên!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            txtSoDem.requestFocus();
            return;
        }
        save = true;
        dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    public void loadData(TourDTO tour) {
        txtTenTour.setText(tour.getTenTour());
        txtGiaTour.setText(String.valueOf(tour.getGia()));
        txtTinhTrang.setText(tour.getTinhTrang());
        txtMoTa.setText(tour.getMoTa());
        txtDiemKH.setText(tour.getDiemKhoiHanh());
        txtDiemDen.setText(tour.getDiemDen());
        cbLoaiTour.setText(tour.getLoaiTour());
        txtSoNgay.setText(String.valueOf(tour.getSoNgay()));
        txtSoDem.setText(String.valueOf(tour.getSoDem()));
    }

    public boolean isSave() {
        return this.save;
    }
    
    public TourDTO getInputData() {
        TourDTO tour = new TourDTO();
        tour.setTenTour(txtTenTour.getText());
        tour.setGia(Float.parseFloat(txtGiaTour.getText()));
        tour.setTinhTrang(txtTinhTrang.getText());
        tour.setMoTa(txtMoTa.getText());
        tour.setDiemKhoiHanh(txtDiemKH.getText());
        tour.setDiemDen(txtDiemDen.getText());
        tour.setLoaiTour(cbLoaiTour.getText());
        tour.setSoNgay(Integer.parseInt(txtSoNgay.getText()));
        tour.setSoDem(Integer.parseInt(txtSoDem.getText()));
        return tour;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.Components.MyButton btnCancel;
    private gui.Components.MyButton btnSubmit;
    private javax.swing.JTextField cbLoaiTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDiemDen;
    private javax.swing.JTextField txtDiemKH;
    private javax.swing.JTextField txtGiaTour;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoDem;
    private javax.swing.JTextField txtSoNgay;
    private javax.swing.JTextField txtTenTour;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
