package gui.form;

import bus.ChiTietHanhKhachBUS;
import bus.HoaDonBUS;
import bus.TourBUS;
import enums.LoaiHanhKhach;
import gui.chart.ModelChart;
import gui.chart.ModelPolarAreaChart;
import gui.components.MyScrollBarUI;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import utils.DateUtils;

public class ThongKeForm extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeForm
     */
    public ThongKeForm() {
        initComponents();
        
        thongKeDoanhThu.addLegend("Doanh thu", Color.decode("#1CB5E0"));
        cbChooseYearThongKeDoanhThu.setModel(new DefaultComboBoxModel<>(new Integer[]{2025, 2024, 2023}));
        cbChooseYearThongKeTour.setModel(new DefaultComboBoxModel<>(new Integer[]{2025, 2024, 2023}));
        cbChooseMonthThongKeTour.setModel(new DefaultComboBoxModel<>(new Object[]{"None", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}));
        
        spTableThongKeTour.getVerticalScrollBar().setUI(new MyScrollBarUI());
        spTableThongKeTour.getVerticalScrollBar().setPreferredSize(new Dimension(8, 0));
        spTableThongKeTour.getViewport().setBackground(Color.white);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTableThongKeTour.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        DefaultTableModel model = new DefaultTableModel(new String[] {"STT", "Mã tour", "Tên tour", "Vé bán ra", "Doanh thu"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableThongKeTour.setModel(model);
        
        if (!java.beans.Beans.isDesignTime()) {
            loadDoanhThuChart();
            loadTKTourTable();
            loadPolarAreaChart();
        } else {
            System.out.println("ThongKeForm đang chạy ở design time mode");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new gui.components.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        thongKeDoanhThu = new gui.chart.Chart();
        cbChooseYearThongKeDoanhThu = new gui.components.CustomComboBox<Integer>();
        jLabel2 = new javax.swing.JLabel();
        panelBorder3 = new gui.components.PanelBorder();
        polarAreaChart = new gui.chart.PolarAreaChart();
        jLabel6 = new javax.swing.JLabel();
        panelBorder4 = new gui.components.PanelBorder();
        jLabel3 = new javax.swing.JLabel();
        spTableThongKeTour = new javax.swing.JScrollPane();
        tableThongKeTour = new gui.components.Table();
        jLabel4 = new javax.swing.JLabel();
        cbChooseYearThongKeTour = new gui.components.CustomComboBox<Integer>();
        cbChooseMonthThongKeTour = new gui.components.CustomComboBox();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1660, 1000));

        panelBorder1.setPreferredSize(new java.awt.Dimension(1000, 470));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Danh thu theo năm");

        cbChooseYearThongKeDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseYearThongKeDoanhThuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Chọn năm");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(thongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbChooseYearThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbChooseYearThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(thongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        polarAreaChart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Thống kê loại hành khách");

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(polarAreaChart, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(polarAreaChart, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Thống kê Tour");

        spTableThongKeTour.setBorder(null);

        tableThongKeTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spTableThongKeTour.setViewportView(tableThongKeTour);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Chọn năm");

        cbChooseYearThongKeTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseYearThongKeTourActionPerformed(evt);
            }
        });

        cbChooseMonthThongKeTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseMonthThongKeTourActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Chọn tháng");

        javax.swing.GroupLayout panelBorder4Layout = new javax.swing.GroupLayout(panelBorder4);
        panelBorder4.setLayout(panelBorder4Layout);
        panelBorder4Layout.setHorizontalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBorder4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbChooseYearThongKeTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbChooseMonthThongKeTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(spTableThongKeTour, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        panelBorder4Layout.setVerticalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChooseYearThongKeTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbChooseMonthThongKeTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(spTableThongKeTour, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbChooseYearThongKeDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseYearThongKeDoanhThuActionPerformed
        loadDoanhThuChart();
    }//GEN-LAST:event_cbChooseYearThongKeDoanhThuActionPerformed

    private void cbChooseYearThongKeTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseYearThongKeTourActionPerformed
        loadTKTourTable();
    }//GEN-LAST:event_cbChooseYearThongKeTourActionPerformed

    private void cbChooseMonthThongKeTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseMonthThongKeTourActionPerformed
        loadTKTourTable();
    }//GEN-LAST:event_cbChooseMonthThongKeTourActionPerformed

    private void loadDoanhThuChart() {
        int year = (int) cbChooseYearThongKeDoanhThu.getSelectedItem();
        float[] data = new HoaDonBUS().thongKeDoanhThuTheoNam(year);
        thongKeDoanhThu.clearChartData();
        for (int i=0; i<12; i++) {
            thongKeDoanhThu.addData(new ModelChart("Tháng" + (i + 1), new double[]{data[i]}));
        }
    }
    
    private void loadTKTourTable() {
        int year = (int) cbChooseYearThongKeTour.getSelectedItem();
        Object month = cbChooseMonthThongKeTour.getSelectedItem();
        LocalDate start;
        LocalDate end;
        if (month instanceof Integer) {
            start = DateUtils.getStartOfMonth(year, (int) month);
            end = DateUtils.getEndOfMonth(year, (int) month);
        } else {
            start = DateUtils.getStartOfYear(year);
            end = DateUtils.getEndOfYear(year);
        }
        DefaultTableModel model = (DefaultTableModel) tableThongKeTour.getModel();
        model.setRowCount(0);
        ArrayList<Object[]> data =  new TourBUS().thongKeTour(start, end);
        for (Object[] row: data) {
            model.addRow(row);
        }
    }
    
    private void loadPolarAreaChart() {
        ArrayList<Object[]> data = new ChiTietHanhKhachBUS().thongKeLoaiHanhKhach();
        Color[] colors = new Color[] {new Color(175, 67, 237), new Color(87, 218, 137), new Color(52, 148, 203), new Color(52, 203, 203)};
        for (int i = 0; i< data.size(); i++) {
            polarAreaChart.addItem(new ModelPolarAreaChart(colors[i], ((LoaiHanhKhach)data.get(i)[0]).getText(), (int) data.get(i)[1]));
        }
        polarAreaChart.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.components.CustomComboBox cbChooseMonthThongKeTour;
    private gui.components.CustomComboBox cbChooseYearThongKeDoanhThu;
    private gui.components.CustomComboBox cbChooseYearThongKeTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private gui.components.PanelBorder panelBorder1;
    private gui.components.PanelBorder panelBorder3;
    private gui.components.PanelBorder panelBorder4;
    private gui.chart.PolarAreaChart polarAreaChart;
    private javax.swing.JScrollPane spTableThongKeTour;
    private gui.components.Table tableThongKeTour;
    private gui.chart.Chart thongKeDoanhThu;
    // End of variables declaration//GEN-END:variables
}
